### ISSUE TITLE
give some git Suggest

### ISSUE THREAD

**Issue by exfly** [biuiko/LedManageSystem#1]
`sqlite.db` and `*.pyc` should be ignore in git. see [git-doc-gitignore](https://git-scm.com/docs/gitignore) and [gitignore.io](https://www.gitignore.io/). You have to much to lean in coding. Fighting!

**Comment by biuiko** [comment]
Thanks for your suggestion.This project will be downloaded by my tutor so I put my database in git.I know I have a lot to learn in coding and I will work hard for it!Thanks again for your suggestion!Fighting !
